set_property PACKAGE_PIN W4 [get_ports choose[0]]
set_property IOSTANDARD LVCMOS33 [get_ports choose[0]]
set_property PACKAGE_PIN V4 [get_ports choose[1]]
set_property IOSTANDARD LVCMOS33 [get_ports choose[1]]
set_property PACKAGE_PIN U4 [get_ports choose[2]]
set_property IOSTANDARD LVCMOS33 [get_ports choose[2]]
set_property PACKAGE_PIN U2 [get_ports choose[3]]
set_property IOSTANDARD LVCMOS33 [get_ports choose[3]]

set_property PACKAGE_PIN V7 [get_ports seg[7]]
set_property IOSTANDARD LVCMOS33 [get_ports seg[7]]
set_property PACKAGE_PIN U7 [get_ports seg[6]]
set_property IOSTANDARD LVCMOS33 [get_ports seg[6]]
set_property PACKAGE_PIN V5 [get_ports seg[5]]
set_property IOSTANDARD LVCMOS33 [get_ports seg[5]]
set_property PACKAGE_PIN U5 [get_ports seg[4]]
set_property IOSTANDARD LVCMOS33 [get_ports seg[4]]
set_property PACKAGE_PIN V8 [get_ports seg[3]]
set_property IOSTANDARD LVCMOS33 [get_ports seg[3]]
set_property PACKAGE_PIN U8 [get_ports seg[2]]
set_property IOSTANDARD LVCMOS33 [get_ports seg[2]]
set_property PACKAGE_PIN W6 [get_ports seg[1]]
set_property IOSTANDARD LVCMOS33 [get_ports seg[1]]
set_property PACKAGE_PIN W7 [get_ports seg[0]]
set_property IOSTANDARD LVCMOS33 [get_ports seg[0]]

set_property PACKAGE_PIN W19 [get_ports BtnL] 
set_property IOSTANDARD LVCMOS33 [get_ports BtnL] 
set_property CLOCK_DEDICATED_ROUTE FALSE [get_nets BtnL]
set_property PACKAGE_PIN U18 [get_ports BtnC] 
set_property IOSTANDARD LVCMOS33 [get_ports BtnC] 
set_property CLOCK_DEDICATED_ROUTE FALSE [get_nets BtnC]
set_property PACKAGE_PIN W5 [get_ports clk] 
set_property IOSTANDARD LVCMOS33 [get_ports clk]
create_clock -add -name sys_clk_pin -period 10.00 -waveform {0 5} {get_ports clk}